### PR TITLE
Added BigBox Dock head menu item to prepare below Auto Home

### PR DESCRIPTION
**Pull request by StefanIGit**

### CODE REVIEW

**Comment by Alex9779** [comment]
I thought about this but I have to say I would like to have a home done in that command too. If you didn't home and execute this command the head can crash into the side or back because he initial position is undefined. IMHO the LCD options should be safe seen individually...

**Comment by StefanIGit** [comment]
You are right, i was planning  to use it like this:
I stop a print for any reason, the i have easy "go away" function..... There should be an option to check if axis are homed, since when you swtich the printer on the lcd says like "x: ?  Y:?  Z:?" before it is homed.  I will look into it.

**Comment by Alex9779** [comment]
Maybe it would be better to include this in the cancel function for the purpose you described... Then it is done on every cancel. Since I only print with OctoPrint I wouldn't need this and have this in the cancel script of OctoPrint...

**Comment by Alex9779** [comment]
This is my OP cancel script:

```
;BigBox Printer End Script Begin
;relies on M83 (use relative extrusion distances)

G91 ; relative positioning
G1 E-1.5 F4200 ; retract
G1 Z10 F360 ; move Z axis by 10mm
G90 ; absolute positioning

;move to dock
T0 ; select extruder 0
G1 X100 Y200 F3000 ; move to position in front of dock
G1 X100 Y235 F3000 ; move into dock

;purge extruder 0
T0 ; select extruder 0
G1 E25 F400 ; extrude 25mm
G1 E-14  F4000 ; retract 14mm very fast

;purge extruder 2
T1 ; select extruder 1
G1 E25 F400 ; extrude 25mm
G1 E-14  F4000 ; retract 14mm very fast

T0 ; select extruder 0
M104 S0 ; turn off extruder 0
T1 ; select extruder 1
M104 S0 ; turn off extruder 1
M140 S0 ; turn off bed
M84 ; disable steppers
M106 S0 ; disable cooling fans
T0 ; select extruder 0

M117 Print complete

;BigBox Printer End Script End
```

**Pull request closed without merging**
